config/routes.rb
Rails.application.routes.draw do
  root 'planets#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :planets, only: [:new, :create, :show, :index]
  resources :reviews, only: [:create]
end

app/models/planet.rb
class Planet < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :user, presence: true

  mount_uploader :photo, PlanetPhotoUploader

  def image
    filename = "#{name.gsub(" ", "_")}.jpg"
    path = "#{Rails.root}/public/images/#{filename}"
    if File.exists?(path)
      return filename
    else
      return photo.url
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  RATINGS = [5, 4, 3, 2, 1]

  belongs_to :planet
  belongs_to :user

  validates :rating, inclusion: { in: RATINGS }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:github]

  has_many :planets
  has_many :reviews

  class << self
    def admin
      return find_admin if find_admin
      return create_admin
    end

    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.image = auth.info.image
      end
    end

    private
    def find_admin
      find_by(email: admin_email)
    end

    def create_admin
      user = new
      user.email = admin_email
      user.password = admin_password
      user.save!
      user
    end

    def admin_email
      ENV["ADMIN_EMAIL"] || "definitelyreal@launchacademy.com"
    end

    def admin_password
      ENV["ADMIN_PASSWORD"] || "longenoughpassword"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    if @planet.save
      redirect_to planet_path(@planet), notice: "New planet, #{@planet.name}, created."
    else
      render :new
    end
  end

  def index
    @planets = Planet.limit(10)
  end

  def show
    @planet = Planet.find(params[:id])
    @review = @planet.reviews.build
  end

  protected
  def planet_params
    params.require(:planet).permit(
      :name,
      :diameter_in_km,
      :mass_in_kg,
      :moons,
      :min_temp_in_c,
      :max_temp_in_c,
      :description,
      :photo
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @planet = Planet.find(review_params[:planet_id])
    @review = @planet.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      flash[:notice] = "Thanks for your input!"
    else
      flash[:error] = "Something is wrong with your review."
    end
    redirect_to @planet
  end

  protected
  def review_params
    params.require(:review).permit(:rating, :body, :planet_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect(@user, event: :authentication)
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlanetReviews</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">PlanetReviews</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if current_user %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'GitHub', user_omniauth_authorize_path(:github) %>
        <% end %>
      </ul>
    </section>
  </nav>

  <% flash.each do |type, message| %>
    <div data-alert class="alert-box <%= type %>">
      <%= message %>
      <%= link_to "x", "#", class: :close %>
    </div>
  <% end %>

  <div class="row">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/planets/index.html.erb
<% @planets.each do |planet| %>
  <div class="small-12 columns">
    <hr />
    <div class="row">
      <div class="small-4 columns">
        <%= image_tag planet.image %>
      </div>
      <div class="small-8 columns">
        <p>Name: <%= link_to planet.name, planet %></p>
        <p>Description: <%= planet.description %></p>
      </div>
    </div>
  </div>
<% end %>

<%= link_to "Add a Planet", new_planet_path %>

app/views/planets/new.html.erb
<% if @planet.errors.any? %>
  <h1>Errors when saving</h1>
  <ul>
  <% @planet.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @planet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :diameter_in_km %>
  <%= f.text_field :diameter_in_km %>

  <%= f.label :mass_in_kg %>
  <%= f.text_field :mass_in_kg %>

  <%= f.label :moons %>
  <%= f.text_field :moons %>

  <%= f.label :min_temp_in_c %>
  <%= f.text_field :min_temp_in_c %>

  <%= f.label :max_temp_in_c %>
  <%= f.text_field :max_temp_in_c %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :photo %>
  <%= f.file_field :photo %>

  <%= f.submit "Create Planet" %>
<% end %>

app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>

<div>
  Mass: <%= @planet.mass_in_kg %> kg
</div>

<div>
  Description: <%= @planet.description %>
</div>

<h2>New Review</h2>

<%= form_for @review do |f| %>
  <%= f.label :rating %>
  <%= f.collection_select :rating, Review::RATINGS, :to_s, :to_s %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.hidden_field :planet_id, value: @planet.id %>

  <%= f.submit %>
<% end %>